id: P4A79CA96
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG4950
  instance_id: http://purl.bdrc.io/resource/IE1KG4950
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - མདོ་དང་རྣམ་འགྲེལ་སྦྱར་བའི་འཕྲོས་དོན་མཚམས་སྦྱོར།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P5617
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  volumes:
    7642384f02154fcfa15260f6f100bf50:
      title: པོད ༡་མདོ་དང་རྣམ་འགྲེལ་སྦྱར་བའི་འཕྲོས་དོན་མཚམས་སྦྱོར
      volume_number: 1
      base_file: UT1KG4950_I1KG5070_0000.txt
      reference: http://purl.bdrc.io/resource/VL9CB3539ADCA2E272
      image_group: I1KG5070
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1KG4950
  - http://purl.bdrc.io/resource/MW1KG4950
  ocr_software: Namsel
created_at: '2021-12-22T10:46:01.409164'
last_modified_at: '2021-12-22T10:46:01.409170'
